### ISSUE TITLE
'stock' variable Data Type question

### ISSUE THREAD

**Issue by jokbalkiller** [coding-Benny/NTACT#2]
https://github.com/coding-Benny/NTACT/blob/9232948b753dca54eeb48e21270e78732e786085/client/js/category.js#L30
stock 변수의 생성 취지가 궁금합니다. 
저는 stock 변수를  메뉴 판매 여부를 결정하는 역할로 이해하였는데 그렇다면  boolean형으로 변환을 하여  true, false 로만 간단하게 관리하는 것이 어떨까요?  코드상으로 봤을 경우 숫자보다는 예외가 적기 때문에  버그가 일어날 확률이 적고 간단한 로직 구현이 가능할 것같습니다. 현실에서도 재고가 있어도 바빠서 잠시 해당 메뉴 판매를 중지 시켜야 하는 경우 등의 상황(재고의 수와 관련없이 컨트롤하여야 하는 상황)이 있을 것같습니다.
혹시 다른 목적이나 의도로 숫자형 변수를 만드신거라면 알려주세요.

**Comment by coding-Benny** [comment]
저는 stock이 메뉴 당 재고 개수를 의미한다고 이해하였습니다. 아마 판매 시작할 때 재고 개수를 업데이트해 두었다가 판매량만큼 차감되면서 0이 되면 sold out 되는 방식을 생각한 것 같습니다.

저는 @jokbalkiller 님의 말씀에 동의하는 바이며, 조금 제 생각을 덧붙이자면 완제품을 판매하기보다는 메뉴를 만드는데 필요한 재료가 소진되는 경우가 일반적이고, 그 재료가 들어가는 메뉴들이 모두 판매 불가 처리되어야 하기 때문에 메뉴마다 stock 개수를 처리하는 방식보다는 @jokbalkiller 님이 말씀하신 것처럼 하는 게 괜찮을 것 같은데 다른 의견 있으시면 말씀해 주세요!

하나 더 말씀드리자면, 제기된 이슈를 반영하여 처리하셨다면 pull request를 하시거나 commit 메시지 끝에 이슈 번호를 적어주시면 자동으로 해당 이슈가 close 됩니다😄 지난 이슈를 close 해 주시지 않아서 제가 처리해 두었으니 참고하셔서 처리해 주세요~~

**Comment by truebliss** [comment]
네 배민이나 요기요에서 카페들어가 보면 재고수가 나오길래 만들었던건데 boolean으로 처리하는게 낫겠네요
DB부분은 백엔드쪽 담당이니까 프론트쪽에서 DB구조짠거를 너무 참고안하셔도 됩니다😂
