### ISSUE TITLE
node_module 파일 경로

### ISSUE THREAD

**Issue by jokbalkiller** [coding-Benny/NTACT#3]
https://github.com/coding-Benny/NTACT/blob/55f1b6ff52e69072c8fe5c1558e5f9efd6e28a38/.gitignore#L4

client/node_module 처럼 되있지 않는 이유가 궁금합니다. 해당 API 마다 node_module 폴더가 각자 존재 하는건가요?

**Comment by coding-Benny** [comment]
구조적인 부분을 잘 모르셔서 일단 로그인 기능을 구현 중이시니 해당 디렉리에 넣고 작업을 하셨던 것 같아요. 어제 제가 login 디렉터리 내부에 있는 것들은 client 밑으로 꺼내고 계속 다른 페이지나 작업들을 이어가시면 될 것 같다고 요청드렸습니다. 종근님께는 공유해드렸었는데 front 담당자 분들도 제가 [유튜브 클론 프로젝트](https://github.com/coding-Benny/react-youtube-clone) 링크 걸어드리니 전체적인 구조 참조하셔서 만들어 보세요!

@9SuJin8 님은 이 부분 처리하시고 commit 메시지에 이슈 번호 #3 적어주셔서 이슈 close 처리해 주세요!

**Comment by coding-Benny** [comment]
아 지금 다시 확인해보니까 수진님께서 디렉터리 처리는 하셨는데 .gitignore 부분을 처리를 미처 못하신 것 같아요! 그 부분은 제가 처리하겠습니다 :)
